export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const SET_USER = 'SET_USER'
export const LOADING_USER = 'LOADING_USER'
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ'

export const SET_ERRORS = 'SET_ERRORS'
export const SET_ERRORS_SIGNUP = 'SET_ERRORS_SIGNUP'
export const SET_ERRORS_LOGIN = 'SET_ERRORS_LOGIN'
export const LOADING_UI = 'LOADING_UI'
export const STOP_LOADING_UI = 'STOP_LOADING_UI'
export const SET_ERRORS_COMMENT = 'SET_ERRORS_COMMENT'
export const SET_ERRORS_POST = 'SET_ERRORS_POST'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const LOADING_DATA = 'LOADING_DATA'
export const SET_SCREAMS = 'SET_SCREAMS'
export const LIKE_SCREAMS = 'LIKE_SCREAMS'
export const UNLIKE_SCREAMS = 'UNLIKE_SCREAMS'
export const NEW_POST = "NEW_POST"
export const DELETE_POST = "DELETE_POST"
export const SET_SCREAM = 'SET_SCREAM'
export const POST_COMMENT = 'POST_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'